### ISSUE TITLE
Can you add array_contains to server side query params list?

### ISSUE THREAD

**Issue by DavidCorrado** [fluttercommunity/firestore_helpers#10]
https://firebase.google.com/docs/firestore/query-data/queries

Looks like it was added in flutter in 0.8.0 of firestore
https://stackoverflow.com/questions/51924896/firestore-flutter-array-contains

Let me know if you need more info.

**Comment by DavidCorrado** [comment]
Not sure if this is the proper place to report issues as this repo is before the current flutter library version of 2.0.7

**Comment by escamoteur** [comment]
I'm a bit busy at the moment, what about making an PR?

**Comment by DavidCorrado** [comment]
Is your latest code pushed to github?  Seems like what is in github is an older version.

**Comment by escamoteur** [comment]
Sure, why do you think?

**Comment by escamoteur** [comment]
@DavidCorrado you are right I found it out today, I had a local data los and it seems I had not pushed to github after publishing the last version, I updated the github today

**Comment by escamoteur** [comment]
it would be awesome if you could make a PR because you have an application that would use it.

**Comment by escamoteur** [comment]
fixed with 3.1.0 thanks to the PR by @netwiser
