### ISSUE TITLE
Limiting query shows furthest document instead of closest

### ISSUE THREAD

**Issue by zxcvbnmmohd** [fluttercommunity/firestore_helpers#14]
I didn't want to make a new issue since the prev issue wasn't really an issue, just me not fully understanding how the function worked.

Below is the function where I can retrieve the values. When using the same latlong value and the radius is high then the values show properly, ie closest to furthest within the radius that is set, but when I set a limit to show only 1 then it shows only the furthest within that radius.

    Stream<List<Mosque>> observeGeoMosques({double lat, double lon, double radius, int limitTo, Function onEmpty, Function onFailure(String e)}) {
    return getDataInArea(
      area: Area(GeoPoint(lat, lon), radius), 
      source: this.mosquesCollection.limit(limitTo),
      locationFieldNameInDB: 'address.geopoint', 
      mapper: (doc) {
        return Mosque().transform(key: doc.documentID, map: doc.data);
      },
      locationAccessor: (mosque) => mosque.address.geopoint,
      distanceMapper: (mosque, distance) {
        mosque.address.distance = distance;
        return mosque;
      },
      sortDecending: true
    );
    }

**Comment by zxcvbnmmohd** [comment]
Sorry, after looking at your example carefully I was able to figure it out! Thanks, great work on this!

**Comment by escamoteur** [comment]
does it change anything if you set sortDecending to false? This seems to be a problem with the limit function of firestore and not something I can change

**Comment by zxcvbnmmohd** [comment]
Ya it worked!
