### ISSUE TITLE
/example is broken.

### ISSUE THREAD

**Issue by kyleorin** [fluttercommunity/firestore_helpers#15]
Aside from the example breaking down when trying to receive the package:
`[example] flutter packages get
Running "flutter packages get" in example...                    
Because firestorehelpertest depends on firestore_helpers from path which doesn't exist (could not find package firestore_helpers at "..\"), version solving failed.`

(managed to get through by deleting the path area)

I receive 2 errors regarding the databaseservice.dart file:
<img width="671" alt="screenshot 2018-12-17 at 15 50 05" src="https://user-images.githubusercontent.com/33470998/50091249-7e69ae00-0213-11e9-97cf-352429f717b1.png">

I found this package exactly what I needed but it needs to be mended before use.

**Comment by escamoteur** [comment]
Hi,
 sorry that it took so long. Because of a local data loss the pub package was no longer in sync with the github this should now be solved.
Cheers
Thomas
