### ISSUE TITLE
Error: No named parameter with the name 'collection'.

### ISSUE THREAD

**Issue by delphiy** [fluttercommunity/firestore_helpers#16]
Error: No named parameter with the name 'collection'.

**Comment by escamoteur** [comment]
Could you please provide a bit more information? What are you trying to do, where do you get this error?

**Comment by escamoteur** [comment]
Hi,
 sorry that it took so long. Because of a local data loss the pub package was no longer in sync with the github this should now be solved.
Cheers
Thomas

**Comment by delphiy** [comment]
Hi,
I used the following code

getDataInArea<FbLocation>(
        collection: locationCollection,
        area: Area(center, radiusInKm),
        locationFieldNameInDB: 'position',
        mapper: (doc) => FbLocation.fromJson(doc.data),
        locationAccessor: (item) => item.position,
        // The distancemapper is applied after the mapper
        distanceMapper: (item, dist) {
          item.distance = dist;
          return item;
        }

    );

///////
collection not exist in getDataInArea method

**Comment by delphiy** [comment]
It works perfect , other question , 

How I can use getDataInArea in firebase cloud function

**Comment by escamoteur** [comment]
Honestly I don't think that it will be possible.
