### ISSUE TITLE
The library works with GeoHash ?

### ISSUE THREAD

**Issue by s3bok** [fluttercommunity/firestore_helpers#28]
Hi
I'm searching a solution to do a Query of  Stores nearly by User position, i tested a library GeoFlutterFire, but i can't add more conditions for example, type's store, name's store, etc. the library don't works, and i found your response in StackOverFlow [Your Response](https://stackoverflow.com/questions/46630507/how-to-run-a-geo-nearby-query-with-firestore)

I'm reading the information about firestore_helpers, it says _"DISCLAIMER: As some users pointed out, FireStore does not correctly compare GeoPoints at this time which lead to more data might be returned from the server than the server-side query intended. "
My Question is, if the library can help me ?

**Comment by aasmoth** [comment]
Hi,
I'm using  GeoFlutterFire that works fine but even with its 3.0 version, it's impossible to upgrade firestores packages. Is Firestore_helpers working correctly with GeoPoint sorting ? What is behind this DISCLAIMER ?
Thanks

**Comment by escamoteur** [comment]
Actually, I haven't worked with Firestore for a long time. So I can't say if they fixed the GeoPoint Sorting.
You always can add an additional client-side filter.
