### ISSUE TITLE
Is this library first loading all data before filtering?

### ISSUE THREAD

**Issue by saharvx9** [fluttercommunity/firestore_helpers#29]
Hi ,
I have theoretic question is this library before filtering loading all data then filter?
or filter the server side then it make all queries more productive and cheaper because if i have 10k users and i want to find the closet one by geopoint i dont want that all my data will return(cost a lot of money)

Best regards sahar :)

**Comment by escamoteur** [comment]
What you define as Query should be executed on the server.
clientsideFilter is executed on the  client.

Often server side queries in firestore has limitations so you have to put part of your condition in the clientSideFilter
