### ISSUE TITLE
Omitted properties in QueryConstraints

### ISSUE THREAD

**Issue by guplersaxanoid** [fluttercommunity/firestore_helpers#31]
Why does the `QueryConstraint` class in `firestore_helpers.dart` not include the properties `arrayContainsAny`, `whereIn`, `whereNotIn` that are defined in the `Query` class of `cloud_firestore` package? 

Is there any conflict happening in the program by adding them?  If yes, what are they? If not, would a pull request to add those properties be welcomed?

**Comment by escamoteur** [comment]
Hi,
I guess that properties were added after I stopped working with FireStore. Sure a PR would be welcome. Also if you are interested to join as a maintainter I would also be very happy because I personally don't use the package at the moment

**Comment by guplersaxanoid** [comment]
@escamoteur I have made the pull request , kindly evaluate them. 

And yes, I would be happy to maintain this particular API, I think there is room for lot more cool features to be added.
