### ISSUE TITLE
GetDataInArea with OrderBy

### ISSUE THREAD

**Issue by nanox77** [fluttercommunity/firestore_helpers#5]
Hello, firstly thanks a lot for this plugin, it's very useful and it works perfectly!. Secondly, i need help. I want to use `getDataInArea` method with `orderBy` from `Firebase`. I need to get `items` from `Firebase` collection orderBy `timestamp` in area. I have the following code:

```
Stream<List<Items>> itemsStream() {
    var sydney = GeoPoint(-33.865143, 151.209900); // Sydney, e.g.
    return getDataInArea(
      area: Area(sydney, 2.0), // I want to search in 2 km, e.g.
      source: firestore.collection('items'), // I need `orderBy` this `items` collection by `timestamp` or whatever property. I try `firestore.collection('items').orderBy('timestamp')` but didn't work *.
      locationFieldNameInDB: 'location', // Required to search in area =)
      mapper: (document) {
        return _buildItemFrom(document); // Map the result.
      },
    );
  }
```

* Error: PlatformException(error, Invalid query. You have an inequality where filter (whereLessThan(), whereGreaterThan(), etc.) on field 'location' and so you must also have 'location' as your first orderBy() field, but your first orderBy() is currently on field 'timestamp' instead., null).

Is there any way to `orderBy` collection when i search in area?

Thank you!

**Comment by escamoteur** [comment]
@nanox77 Hi, great if it helps you with your work. What you encounter is a limitation of firestore. Because of the query based on GeoPoints the the query needs an odering by the geopoints before any other ordering. I added new parameters so you can pass your orderconstraint there. Please try V2.07

```Dart
 Stream<List<Items>> itemsStream() {
    var sydney = GeoPoint(-33.865143, 151.209900); // Sydney, e.g.
    return getDataInArea(
      area: Area(sydney, 2.0), // I want to search in 2 km, e.g.
      source: firestore.collection('items'), // I need `orderBy` this `items` collection by `timestamp` or whatever property. I try `firestore.collection('items').orderBy('timestamp')` but didn't work *.
      locationFieldNameInDB: 'location', // Required to search in area =)
      mapper: (document) {
        return _buildItemFrom(document); // Map the result.
      }
      serverSideOrdering: [new OrderConstraint('timeStamp', false)],
    );
  }
```

**Comment by nanox77** [comment]
Sorry for late response!. I added V2.07 and it worked perfectly!. Thanks for implement my request!
