### ISSUE TITLE
Multiple Constrains

### ISSUE THREAD

**Issue by RBSoftwareBR** [fluttercommunity/firestore_helpers#6]
I'm trying to use multiple constrains but it's not working. please help.

![help print](https://user-images.githubusercontent.com/40797880/45987118-30933e80-c046-11e8-9bd1-b411a4cc1269.png)

Coordenadas Variable 
`[-35.20710125507246, -55.76097692727273, -34.36652154492754, -54.70643147272727]`
```

Stream<List<Desejo>> getEvents(eventCollection,
    {List<QueryConstraint> constraints}) {
  try {
    Query ref = buildQuery(
        collection: eventCollection,
        constraints: constraints,
        orderBy: [
          new OrderConstraint("dataPretendida", true),
          new OrderConstraint('lat', true),
          new OrderConstraint('lng', true)
        ]);
    var r =
        ref.snapshots().map((snapShot) => snapShot.documents.map((eventDoc) {
              Desejo event = Desejo.fromJson(eventDoc.data);
              event.key = eventDoc.documentID;
              return event;
            }).toList());
    r.toList().then((v) {
      print(v.toString());
    });
    return r;
  } on Exception catch (ex) {
    print(ex);
  }
  return null;
}
```

``` 
 getEvents(Firestore.instance.collection('desejos'), constraints: [
    new QueryConstraint(
        field: 'dataPretendida',
        isGreaterThanOrEqualTo: DateTime.now().microsecondsSinceEpoch),
    new QueryConstraint(
        field: 'lat',
        isGreaterThanOrEqualTo: coordenadas[2],
        isLessThanOrEqualTo: coordenadas[0]),
    new QueryConstraint(
        field: 'lng',
        isGreaterThanOrEqualTo: coordenadas[3],
        isLessThanOrEqualTo: coordenadas[1]),
    /*new QueryConstraint(field: 'lng', isGreaterThanOrEqualTo: coordenadas[1]),
    new QueryConstraint(field: 'lng', isLessThanOrEqualTo: coordenadas[3]),*/
  ]);
```

 Error message.
`All where filters other than whereEqualTo() must be on the same field. But you have filters on 'dataPretendida' and 'lat'
        at com.google.firebase.firestore.Query.zza(SourceFile:91)
        at com.google.firebase.firestore.Query.zza(SourceFile:281)
        at com.google.firebase.firestore.Query.whereLessThanOrEqualTo(SourceFile:166)
        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:151)
        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:455)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-25 01:10:26.276 4820-6135/com.rbsoftware.bartner E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    PlatformException(error, All where filters other than whereEqualTo() must be on the same field. But you have filters on 'dataPretendida' and 'lat', null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
    <asynchronous suspension>
    #2      Query.snapshots.<anonymous closure> (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.0/lib/src/query.dart:57:37)
    #3      _runGuarded (dart:async/stream_controller.dart:804:24)
    #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217:7)
    #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:817:19)
    #6      _StreamImpl.listen (dart:async/stream_impl.dart:466:9)
    #7      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:10)
    #8      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:91:16)
    #9      _ForwardingStream.listen (dart:async/stream_pipe.dart:86:12)
    #10     Stream.toList (dart:async/stream.dart:959:10)
    #11     getEvents (package:bartner/elementos/Menu/MeusDesejosPage.dart:84:7)
    #12     PrepDesejosScreen (package:bartner/elementos/Menu/MeusDesejosPage.dart:96:3)
    #13     _MenuPrincipal.getDocumentNearBy.<anonymous closure>.<anonymous closure> (package:bartner/elementos/Menu/MenuPrincipal.dart:177:24)
    #14     State.setState (package:flutter/src/widgets/framework.dart:1125:30)
    #15     _MenuPrincipal.getDocumentNearBy.<anonymous closure> (package:bartner/elementos/Menu/MenuPrincipal.dart:176:7)
    #16     _RootZone.runUnary (dart:async/zone.dart:1381:54)
    #17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
    #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
    #19     Future._propagateToListeners (dart:async/future_impl.dart:662:32)
    #20     Future._complete (dart:async/future_impl.dart:467:7)
    #21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
    #22     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
    <asynchronous suspension>
    #23     Location.getLocation (package:location/location.dart:12:8)
    #24     _MenuPrincipal.getDocumentNearBy (package:bartner/elementos/Menu/MenuPrincipal.dart:156:14)
    #25     _MenuPrincipal.initState (package:bartner/elementos/Menu/MenuPrincipal.dart:188:5)
    #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
    #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
    #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
    #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
    #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
    #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
    #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
    #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)`

**Comment by RBSoftwareBR** [comment]
Found a solution, in short cloud firestore does not do multiple arguments in a query. 
So i had to change my database a little.

**Comment by ROTGP** [comment]
@RBSoftwareBR for the benefit over anyone else who runs into this problem, could you post a short summary of the changes you made?

**Comment by escamoteur** [comment]
@RBSoftwareBR True only an additional isEqual can be added. What I do in that case I use a clientsidefilter. How did you change your DB that you could solve this?

**Comment by RBSoftwareBR** [comment]
I changed my values lat lng from  numbers to GeoPoint object then . . .


```
`Stream<List<EventData>> getEvents(area) {
  try {
    return getDataInArea(
      collection: Firestore.instance.collection("desejos"),
      area: area,
      locationFieldNameInDB: 'geopoint',
      mapper: (eventDoc) {
        Desejo event = Desejo.fromJson(eventDoc.data);
        event.geopoint = eventDoc.data['geopoint'] as GeoPoint;
        event.key = eventDoc.documentID;
        return new EventData(event);
      },
      locationAccessor: (eventData) => eventData.desejo.geopoint,
      distanceMapper: (eventData, distance) {
        eventData.distance = distance;
        return eventData;
      },
      distanceAccessor: (eventData) => eventData.distance,
      //clientSitefilters: (event) =>  event.dataPretendida > DateTime.now() // filer only future events
    );
  } catch (ex) {
    print('ERRO:' + ex.toString());
  }
  return null;
}`
```

then i created a function that filters my list

```
`FilterDesejos(List<Desejo> des) {
    if (listud != null) {
      List<UsuariosDesejo> lud = new List();
      for (UsuariosDesejo ud in listud) {
        lud.add(ud);
      }
      List<Desejo> desejos = new List();
      for (Desejo d in des) {
        if (d.dataPretendida.microsecondsSinceEpoch >
            DateTime.now().microsecondsSinceEpoch) {
          bool hasAction = false;
          for (UsuariosDesejo u in lud) {
            if (u.id_desejo == d.key) {
              if (u.situacao != 'later') {
                hasAction = true;
              }
            }
          }
          bool ageMatche = true;
          for (Usuario u in d.participantes) {
            DateTime agora = DateTime.now();
            DateTime minima = new DateTime(
                agora.year - Helpers.fbUser.minAge.floor(),
                agora.month,
                agora.day);
            DateTime maxima = new DateTime(
                agora.year - Helpers.fbUser.maxAge.floor(),
                agora.month,
                agora.day);
            if (u.idade.microsecondsSinceEpoch >
                minima.microsecondsSinceEpoch) {
              ageMatche = false;
            }
            if (u.idade.microsecondsSinceEpoch <
                maxima.microsecondsSinceEpoch) {
              ageMatche = false;
            }
          }
          if (!hasAction && ageMatche) {
            desejos.add(d);
          }
        }
      }
      if (desejos.length == 0) {
        return null;
      } else {
        return desejos;
      }
    } else {
      return null;
    }
  }`
```

then i just called it like this, (there's a lot of things to improve on this code but it works).

```
`new Container(
            child: new StreamBuilder<List>(
                stream: getEvents(new Area(
                    new GeoPoint(coordenadas[0], coordenadas[1]),
                    Helpers.fbUser.distanciaParceiros)),
                builder: (BuildContext context, AsyncSnapshot<List> snapshot) {
                  if (snapshot.data != null) {
                    if (snapshot.data.length != 0) {
                      Iterable<EventData> j = snapshot.data.toList().reversed;
                      List<Desejo> des = new List();
                      for (var d in j) {
                        des.add(d.desejo);
                      }

                      des = new Helpers().FilterDesejos(des);
                      if (des != null) {
                        machengine = getMatchEngine(des);
                        return new CardStack(
                          matchEngine: machengine,
                        );
                      } else {
                        return new Center(
                            child: new Text(
                          "Sem desejos nestes parâmetros",
                          style: new TextStyle(
                            color: Colors.black,
                            fontFamily: 'bebas-neue',
                            fontSize: 25.0,
                          ),
                        ));
                      }
                    } else {
                      return new Center(
                          child: new Text("Resolvendo Parametros",
                              style: new TextStyle(
                                color: Colors.black,
                                fontFamily: 'bebas-neue',
                                fontSize: 25.0,
                              )));
                    }
                  } else {
                    return new Center(
                        child: new Text(
                      "Sem desejos nos parâmetos atuais",
                      style: new TextStyle(
                        color: Colors.black,
                        fontFamily: 'bebas-neue',
                        fontSize: 25.0,
                      ),
                    ));
                  }
                }),
          )`
```

pic of the changes. 
![solving](https://user-images.githubusercontent.com/40797880/46219844-c0730a00-c31e-11e8-8865-2e3cdeb2f2b6.png)

**Comment by escamoteur** [comment]
@RBSoftwareBR great. Yeah having location be a GeoPoint is crucial to enaböe geographic searches at all.
