### ISSUE TITLE
getDataInArea returns nothing

### ISSUE THREAD

**Issue by ghost** [fluttercommunity/firestore_helpers#7]
Hi, first of all thank you so much such a helpful plugin this really saves me from a lot of works.
I tried to fetch by using `getDataInArea` but it returns nothing. I tried to search for what was wrong but I still can't find it. So, could you tell me what am I missing?

I set data to `Firestore` like so.

```
var lat = 34.702485;
var lng = 135.495951;
Firestore.instance.collection('helper').document('abc').setData({'location': new GeoPoint(lat, lng), 'name': 'Osaka Station'});
```

And fetching like so.

```
  Stream<List<Item>> itemsStream() {
    return getDataInArea(
      source: Firestore.instance.collection('helper'), 
      area: Area(place, 20.0), 
      locationFieldNameInDB: 'location',
      mapper: (document) {
        print(document.exists);
        print(document.data);
      },
      // serverSideOrdering: [new OrderConstraint('timeStamp', false)],
    );
  }
```

This returns nothing and I set breakpoint, this function ends at `area` it won't go further. 
Can you tell what's going on?
Thank you so much again for great plugin.

sincerely,

**Comment by escamoteur** [comment]
Are you using the latest version?
Is timestamp automatically created? I don't see it when you create the data set.
Also please check the debug output if there is a FireStore message that you have to create an index.

**Comment by ghost** [comment]
Yes I'm using 2.0.7.
Sorry for confusion, I'm not creating timestamp. I just copy and pasted example and commented out.
Here is my full code.

```
class Item {
  GeoPoint location;
  String name;
  Item(DocumentSnapshot snapshot) {
    this.location = (snapshot.data)['location'];
    this.name = (snapshot.data)['name'];
  }
}

class _HelperDemoScreen extends StatelessWidget {

   Stream<List<Item>> itemsStream()  {
    var place = GeoPoint(34.657917, 135.519362); 
    return getDataInArea(
      source: Firestore.instance.collection('helper'), 
      area: Area(place, 20.0), 
      locationFieldNameInDB: 'location',
      mapper: (document) {
        print(document.exists);
        print(document.data);
      },
    );
  }

  @override build(BuildContext context){
    return Scaffold(
      appBar: AppBar(
        title: Text("Helper demo"),
      ),
      body: new Center(
        child: Column(
          children: <Widget>[
            new RaisedButton(
              child: new Text('Write'),
              textColor: Colors.white,
              color: Colors.redAccent,
              onPressed: () {
                var lat = 34.702485;
                var lng = 135.495951;
                Firestore.instance.collection('helper').document('ok').setData({'location': new GeoPoint(lat, lng), 'name': 'Osaka Station'});
            },
            ),
            new RaisedButton(
              child: new Text('Read'),
              textColor: Colors.white,
              color: Colors.redAccent,
              onPressed: () {
                itemsStream();
            },
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by escamoteur** [comment]
Did you create an index for location?
Check your debug output if not there is a link that creates it

**Comment by ghost** [comment]
I didn't. 
Usually `Firestore` throws an exception and give me a url to create index but this function doesn't even throw an exception there is no debug output :(
Thank you for your help.

**Comment by ghost** [comment]
Do you have any full example?
I couldn’t find example folder.

**Comment by escamoteur** [comment]
I think I know why :-) you have to listen on the returned Stream otherwise you won't get any values :-)

**Comment by ghost** [comment]
I’m sorry what do you mean?
Returning getDataInArea and mapper are not enough?

**Comment by escamoteur** [comment]
Your problem is that `itemsStream` just returns a stream. Firebase will only issue data if somone listens to the stream
Just do

```Dart
              onPressed: () {
                itemsStream().listen();
            },
```

**Comment by ghost** [comment]
It worked  thank you so much you made my day!
Is there any way to limit number of documents for fetching?
In `Firestore` normally do like `db..limit(8);`

**Comment by escamoteur** [comment]
I don't think its possible to limit the number of documents on the stream interface of firestore besides using additional query constraint. But I may be wrong there. Me too would have to google for this a while.
Instead of listening you can also use the returned stream directly in a StreamBuilder  Widget.

It seems that you are not that familiar with the concept of Streams so I recommend to read my blog;

https://www.burkharts.net/apps/blog/fundamentals-of-dart-streams/
https://www.burkharts.net/apps/blog/rxdart-magical-transformations-of-streams/
