### ISSUE TITLE
radiusInKilometers 120.0km returns 400.0 km location

### ISSUE THREAD

**Issue by ghost** [fluttercommunity/firestore_helpers#8]
I'm trying to fetch document inside circle of 120.0 km.
But it returns 400.0 km away.
Is this a bug or I'm making some mistake?

This is Osaka Abeno.
```
   var lat = 34.643839; 
   var lng = 135.512383;
   var area = GeoPoint(lat, lng);
```

This is Tokyo Station.
```
   var lat = 35.681167; 
   var lng = 139.767052;
   var area = GeoPoint(lat, lng);
```

I searched these distance in google map and it returns over 400 km.
I fetched like so.

```
Stream<List<Items>> itemsStream() {
    return getDataInArea(
    area: Area(area, 120.0), 
    source: Firestore.instance.collection('items'), 
      locationFieldNameInDB: 'location', 
      mapper: (document) {
        print(document.data);
      },
    );
  }
```

**Comment by escamoteur** [comment]
Hmm that is strange. Will check it tomorrow

**Comment by ghost** [comment]
Thank you.
I appreciate it.

**Comment by ghost** [comment]
I don’t mean to rush but do you have any update?

**Comment by escamoteur** [comment]
What value does aera have?

**Comment by ghost** [comment]
Sorry for late response I didn't get email notification somehow.
area is Osaka Abeno.
I set iPhone simulator's current location to Osaka Abeno. But it returns Tokyo which is 400km away.

**Comment by escamoteur** [comment]
Hi,

I created a little example project in this repo now:

![image](https://user-images.githubusercontent.com/16635729/47437841-a4417c00-d7a9-11e8-9ac2-511848edf1e0.png)

with 410km radius I get both cities back if I change it to 400 only Tokyo

![image](https://user-images.githubusercontent.com/16635729/47437950-cf2bd000-d7a9-11e8-9674-2623f8e0926a.png)



I also tried 120km and I don't get Osaka. The same if I set the current position to Osaka, I don't see Tokyo with an radius of <410km

**Comment by ghost** [comment]
HI, sorry again. 
I tried that again but still return Tokyo. 
Could you share your code?
I hate to say but could you run this code? 
This is exactly the same code that I ran.

```
 final GeoPoint location = GeoPoint(34.649252, 135.539863);
 final Area area = Area(location, 120.0);
 return getDataInArea(
    area: area,
    source: Firestore.instance.collection('helper'), 
      locationFieldNameInDB: 'location', 
      mapper: (document) {
        print(document.data);
       // return 
       // flutter: {name: Tennoji Station, location: Instance of 'GeoPoint'}
      // flutter: {name: Osaka Station, location: Instance of 'GeoPoint'} 
      // flutter: {name: Tokyo Station, location: Instance of 'GeoPoint'}
      },
    );
  }
```

And this my `Firestore` data looks like.
![2018-11-04 9 46 52](https://user-images.githubusercontent.com/41893584/47958814-d6a77080-e016-11e8-95c2-e35aedb23cca.png)
![2018-11-04 9 47 03](https://user-images.githubusercontent.com/41893584/47958815-dc04bb00-e016-11e8-9091-de5a26e58753.png)
![2018-11-04 9 47 20](https://user-images.githubusercontent.com/41893584/47958816-df984200-e016-11e8-84b7-02e999a9b87f.png)

I'm sorry but hope you could help.
Thank you so much.

**Comment by escamoteur** [comment]
Hi,

the code is in the example project of this repository
I have honestly no idea why it does not work for you. Your code looks like mine

**Comment by ghost** [comment]
Thank you for replying. 
Yeah it's weird.
Thanks anyway I'll figure it out somehow!
